import React, { useState } from 'react';
import {
  HelpCircle,
  Search,
  ChevronDown,
  ChevronUp,
  BookOpen,
  FileText,
  ArrowRight,
  ShieldCheck,
  ExternalLink,
} from 'lucide-react';
import { useApp } from '../../context/AppContext';

export const ResourcesPage: React.FC = () => {
  const { navigateTo } = useApp();
  const [activeFaqCategory, setActiveFaqCategory] = useState<string>('ALL');
  const [faqSearch, setFaqSearch] = useState<string>('');
  const [openFaqIndex, setOpenFaqIndex] = useState<number | null>(0);

  const faqs = [
    {
      category: 'CUSTOMS',
      question: 'What is Form M and when is it required in Nigeria?',
      answer:
        'Form M is a mandatory statutory electronic documentation generated by authorized commercial banks on the Nigeria Single Window Trade Portal for all legitimate imports into Nigeria. It must be initiated and approved before cargo is loaded at the port of origin.',
    },
    {
      category: 'CUSTOMS',
      question: 'What is a Pre-Arrival Assessment Report (PAAR)?',
      answer:
        'PAAR is an official customs valuation document issued by the Nigeria Customs Service (NCS) headquarters in Abuja. It confirms the correct classification (HS Code), duty percentage, and value of the consignment so that terminal release duty can be paid.',
    },
    {
      category: 'SHIPPING',
      question: 'How long does air freight take from London Heathrow to Lagos?',
      answer:
        'Priority scheduled air freight typically takes 2 to 4 business days from dispatch at LHR to arrival at the NAHCO or SAHCO cargo terminals at Murtala Muhammed Airport in Lagos. Priority customs clearing usually takes an additional 24 to 48 hours.',
    },
    {
      category: 'SHIPPING',
      question: 'What is the difference between FCL and LCL ocean shipping?',
      answer:
        'FCL (Full Container Load) means you lease an entire 20ft or 40ft container exclusively for your cargo. LCL (Less than Container Load) allows you to pay only for the volume (CBM) your cargo occupies inside a shared container with other shippers.',
    },
    {
      category: 'AUTOTRADE',
      question: 'Can Haryor-Mih inspect and buy vehicles from US auctions like Copart or Manheim?',
      answer:
        'Yes! Through our licensed overseas dealer accounts, we inspect, bid, purchase, handle title verification with US Customs, transport to port, and ship via RoRo or container vessels directly to Lagos with full duty clearance.',
    },
    {
      category: 'PRICING',
      question: 'Are there hidden charges or unexpected terminal fees?',
      answer:
        'No. Haryor-Mih provides transparent, itemized quotations that explicitly detail international freight, carrier terminal handling charges (THC), shipping line demurrage deposits, and customs duties.',
    },
    {
      category: 'GENERAL',
      question: 'Do you offer doorstep delivery outside of Lagos?',
      answer:
        'Yes. Through our dedicated interstate haulage fleet and regional logistics partners, we deliver cleared containers and cargo to Abuja, Kano, Port Harcourt, Ibadan, Enugu, and all 36 Nigerian states.',
    },
  ];

  const articles = [
    {
      id: 'form-m-guide',
      title: 'Complete Guide to Processing Form M and PAAR for Nigeria Commercial Imports',
      category: 'Customs Clearance',
      readTime: '6 min read',
      date: 'Updated for 2026',
      summary:
        'A comprehensive step-by-step walkthrough of Central Bank of Nigeria trade portal guidelines, commercial invoices, and avoiding port clearance delays.',
    },
    {
      id: 'car-import-guide',
      title: 'How to Import Foreign-Used and Brand New Vehicles into Lagos Ports',
      category: 'AutoTrade & RoRo',
      readTime: '8 min read',
      date: 'Updated for 2026',
      summary:
        'From US auction bidding to RoRo vessel loading at Newark or Tilbury, customs VIN duty valuation, and terminal exit at PTML Lagos.',
    },
    {
      id: 'container-guide',
      title: 'Ocean Shipping: 20ft vs 40ft High Cube Container Selection Guide',
      category: 'Freight Forwarding',
      readTime: '5 min read',
      date: 'Updated for 2026',
      summary:
        'Understand payload limits, internal cubic capacity, and how choosing the right container size optimizes ocean freight expenditure.',
    },
    {
      id: 'avoid-demurrage',
      title: 'Top 5 Ways Commercial Importers Can Avoid Costly Port Demurrage in Lagos',
      category: 'Supply Chain Advisory',
      readTime: '7 min read',
      date: 'Updated for 2026',
      summary:
        'Strategies from licensed customs brokers on pre-arrival documentation, terminal transfer scheduling, and single goods declarations.',
    },
  ];

  const filteredFaqs = faqs.filter((f) => {
    const matchesCategory = activeFaqCategory === 'ALL' || f.category === activeFaqCategory;
    const matchesSearch =
      f.question.toLowerCase().includes(faqSearch.toLowerCase()) ||
      f.answer.toLowerCase().includes(faqSearch.toLowerCase());
    return matchesCategory && matchesSearch;
  });

  return (
    <div id="resources-page" className="bg-transparent min-h-screen py-12 text-slate-100">
      <div className="max-w-6xl mx-auto px-4 sm:px-6">
        {/* Header */}
        <div className="text-center max-w-3xl mx-auto mb-12">
          <div className="text-xs font-bold text-orange-400 tracking-widest uppercase mb-1">
            Knowledge Center &amp; Shipper Intelligence
          </div>
          <h1 className="text-3xl sm:text-5xl font-extrabold text-white tracking-tight font-['Montserrat']">
            RESOURCES &amp; FREIGHT FAQ
          </h1>
          <p className="text-xs sm:text-sm text-white/70 mt-3 leading-relaxed">
            Essential guides, regulatory customs insights, and answers to frequently asked questions about international shipping, customs, and vehicle importation.
          </p>
        </div>

        {/* Featured Educational Articles */}
        <div className="mb-14">
          <div className="flex items-center justify-between mb-6">
            <h2 className="text-xl sm:text-2xl font-extrabold text-white font-['Montserrat']">
              Featured Shipping &amp; Customs Guides
            </h2>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {articles.map((art) => (
              <div
                key={art.id}
                className="bg-white/[0.06] backdrop-blur-2xl rounded-3xl p-6 border border-white/15 shadow-2xl hover:border-orange-500/40 transition flex flex-col justify-between text-white"
              >
                <div>
                  <div className="flex items-center justify-between text-[11px] mb-2">
                    <span className="font-extrabold text-orange-400 uppercase tracking-wider">
                      {art.category}
                    </span>
                    <span className="text-white/50">{art.readTime}</span>
                  </div>
                  <h3 className="text-base font-bold text-white hover:text-orange-400 transition">
                    {art.title}
                  </h3>
                  <p className="text-xs text-white/70 mt-2 leading-relaxed">
                    {art.summary}
                  </p>
                </div>

                <div className="pt-4 mt-4 border-t border-white/10 flex items-center justify-between text-xs">
                  <span className="text-white/50 font-medium">{art.date}</span>
                  <button
                    onClick={() => navigateTo('/quote')}
                    className="font-bold text-orange-400 hover:text-orange-300 flex items-center gap-1 transition cursor-pointer"
                  >
                    Apply to Quote <ArrowRight className="w-3.5 h-3.5" />
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Interactive FAQ Section */}
        <div className="bg-white/[0.06] backdrop-blur-2xl rounded-3xl border border-white/15 p-6 sm:p-10 shadow-2xl text-white">
          <div className="text-center max-w-xl mx-auto mb-8">
            <div className="w-10 h-10 rounded-xl bg-orange-500/20 border border-orange-500/30 text-orange-400 flex items-center justify-center mx-auto mb-2">
              <HelpCircle className="w-5 h-5" />
            </div>
            <h2 className="text-2xl font-extrabold text-white font-['Montserrat']">
              Frequently Asked Questions
            </h2>
            <p className="text-xs text-white/60 mt-1">
              Have questions about customs documents, transit windows, or auto shipping?
            </p>

            {/* Search Box */}
            <div className="relative mt-4">
              <input
                type="text"
                placeholder="Search questions or keywords..."
                value={faqSearch}
                onChange={(e) => setFaqSearch(e.target.value)}
                className="w-full px-4 py-2.5 bg-white/[0.05] border border-white/15 rounded-xl text-xs text-white placeholder-white/40 focus:outline-none focus:border-orange-500/50 backdrop-blur-md"
              />
              <Search className="w-4 h-4 text-white/40 absolute right-3.5 top-3" />
            </div>

            {/* Category Filter Chips */}
            <div className="flex flex-wrap items-center justify-center gap-2 mt-4">
              {['ALL', 'CUSTOMS', 'SHIPPING', 'AUTOTRADE', 'PRICING', 'GENERAL'].map((cat) => (
                <button
                  key={cat}
                  onClick={() => setActiveFaqCategory(cat)}
                  className={`px-3 py-1 rounded-lg text-[11px] font-bold transition cursor-pointer ${
                    activeFaqCategory === cat
                      ? 'bg-gradient-to-r from-orange-500 to-amber-600 text-white shadow-md shadow-orange-500/20'
                      : 'bg-white/[0.06] hover:bg-white/15 text-white/70 border border-white/10'
                  }`}
                >
                  {cat}
                </button>
              ))}
            </div>
          </div>

          {/* Accordion Questions */}
          <div className="space-y-3 max-w-3xl mx-auto">
            {filteredFaqs.map((faq, index) => {
              const isOpen = openFaqIndex === index;
              return (
                <div
                  key={index}
                  className="border border-white/10 rounded-2xl overflow-hidden backdrop-blur-md transition"
                >
                  <button
                    onClick={() => setOpenFaqIndex(isOpen ? null : index)}
                    className="w-full px-5 py-4 text-left flex items-center justify-between gap-4 bg-white/[0.04] hover:bg-white/[0.08] transition cursor-pointer"
                  >
                    <span className="text-xs sm:text-sm font-bold text-white">
                      {faq.question}
                    </span>
                    {isOpen ? (
                      <ChevronUp className="w-4 h-4 text-orange-400 shrink-0" />
                    ) : (
                      <ChevronDown className="w-4 h-4 text-white/50 shrink-0" />
                    )}
                  </button>
                  {isOpen && (
                    <div className="px-5 pb-5 pt-2 text-xs text-white/75 leading-relaxed bg-white/[0.02] border-t border-white/10">
                      {faq.answer}
                    </div>
                  )}
                </div>
              );
            })}

            {filteredFaqs.length === 0 && (
              <div className="text-center py-8 text-xs text-white/50">
                No questions found matching your search. Please ask our live WhatsApp helpdesk!
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};
